# -*- coding: utf-8 -*-
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ad1Uk-5_fWGbRTTtvm14Vv-2KaG8bSX9
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

data= pd.read_csv("/content/IMDB Dataset.csv (1).zip")

texts = data["review"].astype(str)
sentiments = data["sentiment"]
encoder = LabelEncoder()
y = encoder.fit_transform(sentiments)
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(texts)
X = tokenizer.texts_to_sequences(texts)
X = pad_sequences(X, maxlen=200)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = Sequential()

model.add(
    Embedding(
        input_dim=5000,
        output_dim=64,
        input_length=200
    )
)

model.add(SimpleRNN(64))

model.add(Dense(1, activation='sigmoid'))

# Compile model
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Train model
model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=32
)

# Evaluate
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

text = ["worst bad okva iruku"]

seq = tokenizer.texts_to_sequences(text)

pad = pad_sequences(seq, maxlen=200)

prediction = model.predict(pad)

if prediction[0][0] > 0.5:
    print("Positive Review")
else:
    print("Negative Review")









































